// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJoVpi5Ng9QYLV0kzRfBxr2257kZIuKNY',
    appId: '1:606163287661:web:c4f4b242b7de5bb1038964',
    messagingSenderId: '606163287661',
    projectId: 'kannan-4a98b',
    authDomain: 'kannan-4a98b.firebaseapp.com',
    databaseURL: 'https://kannan-4a98b-default-rtdb.firebaseio.com',
    storageBucket: 'kannan-4a98b.firebasestorage.app',
    measurementId: 'G-7ZDVYBV0SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9SK-KQfBNe6ok17XpqlWwjpdYeyex_gY',
    appId: '1:606163287661:android:837ac05aad1b696d038964',
    messagingSenderId: '606163287661',
    projectId: 'kannan-4a98b',
    databaseURL: 'https://kannan-4a98b-default-rtdb.firebaseio.com',
    storageBucket: 'kannan-4a98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcSHFCTicq47y8FcEEtJjEoTwhZG4tiA',
    appId: '1:606163287661:ios:dacc7be8fde0bb8f038964',
    messagingSenderId: '606163287661',
    projectId: 'kannan-4a98b',
    databaseURL: 'https://kannan-4a98b-default-rtdb.firebaseio.com',
    storageBucket: 'kannan-4a98b.firebasestorage.app',
    iosClientId: '606163287661-bkm90ikkg2a8a8eis60v82rfve65vddu.apps.googleusercontent.com',
    iosBundleId: 'com.example.editorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJoVpi5Ng9QYLV0kzRfBxr2257kZIuKNY',
    appId: '1:606163287661:web:e68b0bc77a1a1060038964',
    messagingSenderId: '606163287661',
    projectId: 'kannan-4a98b',
    authDomain: 'kannan-4a98b.firebaseapp.com',
    databaseURL: 'https://kannan-4a98b-default-rtdb.firebaseio.com',
    storageBucket: 'kannan-4a98b.firebasestorage.app',
    measurementId: 'G-4G3NJ6TSFK',
  );
}
